version: '3.8'

services:
  backend:
    image: dashboard-raspberry-backend
    ports:
      - "3001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - ms-get-temperature-and-humidify

  ms-get-temperature-and-humidify:
    image: ms-get-temp-and-humd
    ports:
      - "5000:5000"
